jobs:
  build:
    working_directory: ~/cache-test
    docker:
      - image: circleci/node:14
    steps:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn start
    
